apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapplication-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goapplication
  template:
    metadata:
      labels:
        app: goapplication
    spec:
      containers:
      - name: goapplication
        image: luiscoco/myappgolangmicroservice:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: goapplication-config
              key: config.json
      volumes:
      - name: config-volume
        configMap:
          name: goapplication-config
