apiVersion: v1
kind: Service
metadata:
  name: goapplication-service
spec:
  selector:
    app: goapplication
  ports:
    - protocol: TCP
      port: 80  # The port the service is exposed on
      targetPort: 8081  # The target port on the container
  type: LoadBalancer  # Use NodePort or ClusterIP for internal-only access
